# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BusCheck' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BusCheck

  target 'BusCheck-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BusCheckTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BusCheck-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BusCheck-tvOS

  target 'BusCheck-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
